# Generated by Django 5.0.3 on 2024-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("published_at", models.DateTimeField()),
                ("thumbnails", models.JSONField()),
            ],
        ),
    ]
